BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repositories.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers;

[Area("Admin")]
public class CoverTypeController : Controller
{
    readonly IUnitOfWork _db;
    public CoverTypeController(IUnitOfWork unit)
    {
        _db = unit;
    }
    public IActionResult Index()
    {
        var coverTypes = _db.CoverTypeRepository.GetAll();
        return View(coverTypes);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CoverType coverType)
    {
        if (ModelState.IsValid)
        {
            _db.CoverTypeRepository.Add(coverType);
            TempData["success"] = "Cover type has been created!";
            _db.Save();

            return RedirectToAction(nameof(Index));
        }

        return View(coverType);
    }

    public IActionResult Edit(int? id)
    {
        if (id is null || id == 0)
            return NotFound();

        var coverType = _db.CoverTypeRepository.GetFirstOrDefault(c => c.Id == id);

        if (coverType is null)
            return NotFound();

        return View(coverType);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(CoverType coverType)
    {
        if (ModelState.IsValid)
        {
            _db.CoverTypeRepository.Update(coverType);
            TempData["success"] = "CoverType has been edited!";
            _db.Save();

            return RedirectToAction(nameof(Index));
        }

        return View(coverType);
    }

    public IActionResult Delete(int? id)
    {
        if (id is null || id == 0)
            return NotFound();

        var category = _db.CoverTypeRepository.GetFirstOrDefault(c => c.Id == id);

        if (category is null)
            return NotFound();

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        if (id is null || id == 0)
            return NotFound();

        var coverType = _db.CoverTypeRepository.GetFirstOrDefault(c => c.Id == id);

        if (coverType is null)
            return NotFound();

        _db.CoverTypeRepository.Remove(coverType);
        TempData["success"] = "CoverType has been deleted!";
        _db.Save();

        return RedirectToAction(nameof(Index));
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-2 mt-3">
        <div class="row">
            <h2 class="text-primary">Create cover type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" type="submit">Create new cover type</button>
        <a class="btn btn-secondary" asp-controller="CoverType" asp-action="Index">Back to list</a> 
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType
@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-2 mt-3">
        <div class="row">
            <h2 class="text-primary">Delete cover type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
        <button class="btn btn-danger" type="submit">Delete category</button>
        <a class="btn btn-secondary" asp-controller="CoverType" asp-action="Index">Back to list</a> 
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType
@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="Edit">
    <div class="border p-2 mt-3">
        <div class="row">
            <h2 class="text-primary">Update cover type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-primary" type="submit">Update cover type</button>
        <a class="btn btn-secondary" asp-controller="CoverType" asp-action="Index">Back to list</a> 
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>

@{
    ViewData["Title"] = "Index";
}


<div class="row mt-4 mb-4">
    <div class="col-6">
        <h2 class="text-primary">Cover type list</h2>
    </div>
    <div class="col-6 text-end">
        <a class="btn btn-primary" asp-controller="CoverType" asp-action="Create">
            <i class="bi bi-plus-circle m-1"></i>
            <span>Create new cover type</span>
        </a>
    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">Cover type name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var coverType in Model)
        {
            <tr>
                <td>@coverType.Name</td>
                <th>
                    <a class="btn btn-primary" asp-route-id="@coverType.Id" asp-action="Edit">
                        <i class="bi bi-pencil-square"></i>
                        Edit
                    </a>
                    <a class="btn btn-danger" asp-route-id="@coverType.Id" asp-action="Delete">
                        <i class="bi bi-trash3"></i>
                        Delete
                    </a>
                </th>
            </tr>
        }
    </tbody>
</table>